<?php
/**
 * report_print_layout.php
 * 
 * Shared report layout components for standardized PDF/Print output.
 * Include this file in any page that needs printable reports.
 * 
 * Usage:
 *   1. Include this file: include 'includes/report_print_layout.php';
 *   2. Call renderPrintStyles() in <head> or <style> block
 *   3. Call renderPrintHeader($title) where you want the print header
 *   4. Call renderPrintFooter($preparedBy, $preparedByRole) where you want the footer
 */

/**
 * Renders the standard print CSS styles.
 * Call this inside a <style> tag or in the <head>.
 */
function renderPrintStyles(): string {
    return <<<'CSS'
/* PRINT SPECIFIC STYLES (Standardized Layout) */
@media print {
    @page { margin: 0.5in; size: auto; }
    body {
        background-color: white !important;
        color: black !important;
        padding: 0 !important;
        -webkit-print-color-adjust: exact;
    }

    .report-container {
        box-shadow: none !important;
        padding: 0 !important;
        width: 100% !important;
        max-width: none !important;
    }

    /* Hide UI elements */
    .no-print { display: none !important; }

    /* Show print-only elements */
    .print-only { display: block !important; }

    /* Reset main layout for print */
    main {
        margin: 0 !important;
        padding: 0 !important;
        width: 100% !important;
    }

    /* Table Styling for Print */
    table { width: 100% !important; border-collapse: collapse !important; font-size: 10pt !important; }
    thead tr { background-color: #f3f4f6 !important; }
    thead th {
        border: 1px solid #9ca3af !important;
        padding: 8px !important;
        color: black !important;
        font-weight: bold !important;
        text-transform: uppercase !important;
    }
    tbody td {
        border: 1px solid #e5e7eb !important;
        padding: 8px !important;
        color: black !important;
    }

    /* Metadata tables in the header should not show borders */
    .report-meta-table, .report-meta-table td, .report-meta-table th { border: none !important; box-shadow: none !important; }

    /* Footer Spacing */
    .print-footer { margin-top: 50px !important; page-break-inside: avoid; }
}

// Ensure session is started for helper functions that may access session data
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

/* Logo Sizing (applies in print and preview) */
.print-logo { height: 80px; width: auto; margin: 0 auto 10px auto; display: block; }
CSS;
}

/**
 * Renders the standardized print header with logo, title, tagline, date, and optional project metadata.
 *
 * @param string $title The report title (e.g., "Inventory Masterlist")
 * @param array $metadata Optional associative array with keys: project_name, project_code, report_type, generated_by
 * @param string $dateElementId Optional ID for the date span (default: 'print-date')
 * @return string HTML markup for the print header
 */
function renderPrintHeader(string $title, array $metadata = [], string $dateElementId = 'print-date'): string {
    $escapedTitle = htmlspecialchars($title);
    
    // Build metadata section if data is provided
    $metadataHtml = '';
    if (!empty($metadata)) {
        $projectName = htmlspecialchars($metadata['project_name'] ?? 'N/A');
        $projectCode = htmlspecialchars($metadata['project_code'] ?? 'N/A');
        $reportType = htmlspecialchars($metadata['report_type'] ?? $title);
        $generatedBy = htmlspecialchars($metadata['generated_by'] ?? 'System');
        
        $metadataHtml = <<<META
    <div class="grid grid-cols-2 gap-8 mb-8 text-sm text-left">
        <div>
            <table class="w-full report-meta-table">
                <tr>
                    <td class="font-bold text-slate-500 py-1 w-32">Project:</td>
                    <td class="font-bold text-slate-900 py-1">{$projectName}</td>
                </tr>
                <tr>
                    <td class="font-bold text-slate-500 py-1">Project Code:</td>
                    <td class="text-slate-700 py-1">{$projectCode}</td>
                </tr>
            </table>
        </div>
        <div>
            <table class="w-full report-meta-table">
                <tr>
                    <td class="font-bold text-slate-500 py-1 w-32">Report Type:</td>
                    <td class="font-bold text-slate-900 py-1">{$reportType}</td>
                </tr>
                <tr>
                    <td class="font-bold text-slate-500 py-1">Generated By:</td>
                    <td class="text-slate-700 py-1">{$generatedBy}</td>
                </tr>
            </table>
        </div>
    </div>
META;
    }
    
    return <<<HTML
<div class="print-only hidden mb-6">
    <div class="text-center border-b-2 border-slate-800 pb-6 mb-8">
        <img src="../../assets/images/nobg_logo.png" alt="ICMIS Logo" class="print-logo" onerror="this.style.display='none';">
        <h1 class="text-2xl font-black uppercase tracking-wide text-slate-900 mt-2">{$escapedTitle}</h1>
        <p class="text-sm font-medium text-slate-500 uppercase tracking-widest">Integrated Construction Management Information System</p>
        <p class="text-xs text-slate-400 mt-1">Generated on: <span id="{$dateElementId}"></span></p>
    </div>
{$metadataHtml}
</div>
HTML;
}

/**
 * Renders the standardized 3-column print footer with signature lines.
 *
 * @param string $preparedBy Name of the person who prepared the report
 * @param string $preparedByRole Role/title of the preparer (e.g., "Inventory Manager")
 * @param string $verifiedByRole Role of verifier (default: "Project Engineer")
 * @param string $approvedByRole Role of approver (default: "Project Manager")
 * @return string HTML markup for the print footer
 */
function renderPrintFooter(
    string $preparedBy = 'System',
    string $preparedByRole = 'Generated User',
    string $verifiedByRole = 'Project Engineer',
    string $approvedByRole = 'Project Manager'
): string {
    // Attempt to infer preparer if default value is used
    if (empty($preparedBy) || $preparedBy === 'System') {
        if (!empty($_SESSION['user_name'])) {
            $preparedBy = $_SESSION['user_name'];
        } elseif (!empty($_SESSION['user_id']) && defined('DB_HOST')) {
            $uid = intval($_SESSION['user_id']);
            $preparedBy = 'System';
            $conn = @new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
            if ($conn && !$conn->connect_error) {
                $q = $conn->prepare('SELECT full_name FROM icmis_users WHERE user_id = ? LIMIT 1');
                if ($q) {
                    $q->bind_param('i', $uid);
                    $q->execute();
                    $res = $q->get_result();
                    if ($res && $res->num_rows > 0) {
                        $r = $res->fetch_assoc();
                        if (!empty($r['full_name'])) $preparedBy = $r['full_name'];
                    }
                    $q->close();
                }
                $conn->close();
            }
        }
    }

    $escapedPreparedBy = htmlspecialchars($preparedBy);
    $escapedPreparedByRole = htmlspecialchars($preparedByRole);
    $escapedVerifiedByRole = htmlspecialchars($verifiedByRole);
    $escapedApprovedByRole = htmlspecialchars($approvedByRole);

    return <<<HTML
<div class="print-footer mt-12 pt-8 print-only hidden">
    <div class="grid grid-cols-3 gap-8">
        <div class="text-center">
            <p class="text-xs font-bold text-slate-500 uppercase mb-12">Prepared By:</p>
            <div class="border-b border-slate-800 w-3/4 mx-auto"></div>
            <p class="text-sm font-bold mt-2 text-slate-900 uppercase">{$escapedPreparedBy}</p>
            <p class="text-xs text-slate-500">{$escapedPreparedByRole}</p>
        </div>

        <div class="text-center">
            <p class="text-xs font-bold text-slate-500 uppercase mb-12">Verified By:</p>
            <div class="border-b border-slate-800 w-3/4 mx-auto"></div>
            <p class="text-sm font-bold mt-2 text-slate-900 uppercase">___________</p>
            <p class="text-xs text-slate-500">{$escapedVerifiedByRole}</p>
        </div>

        <div class="text-center">
            <p class="text-xs font-bold text-slate-500 uppercase mb-12">Approved By:</p>
            <div class="border-b border-slate-800 w-3/4 mx-auto"></div>
            <p class="text-sm font-bold mt-2 text-slate-900 uppercase">___________</p>
            <p class="text-xs text-slate-500">{$escapedApprovedByRole}</p>
        </div>
    </div>
</div>
HTML;
}

/**
 * Renders the standard printReport() JavaScript function.
 * 
 * @param string $dateElementId The ID of the date element to update (default: 'print-date')
 * @return string JavaScript code for the printReport function
 */
function renderPrintReportScript(string $dateElementId = 'print-date'): string {
    return <<<JS
function printReport() {
    const dateEl = document.getElementById('{$dateElementId}');
    if (dateEl) {
        const now = new Date();
        dateEl.innerText = now.toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric', 
            hour: '2-digit', 
            minute: '2-digit' 
        });
    }
    window.print();
}
JS;
}
